import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import koneksi.konek;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
        
public class siswa extends javax.swing.JFrame {

    /**
     * Creates new form siswa
     */
    public siswa() {
        initComponents();
        datatable();
    }
    private void datatable(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("NISN");
        tbl.addColumn("Nama");
        tbl.addColumn("NIK");
        tbl.addColumn("Tempat, Tanggal Lahir");
        tbl.addColumn("Jurusan");
        tbl.addColumn("Jenis Kelamin");
        tbl.addColumn("Agama");
        tbl.addColumn("Sekolah Asal");
        tbl.addColumn("No Handphone");
        tbl.addColumn("Alamat");
        table.setModel(tbl);
        try{
            Statement statement = (Statement) konek.getKonek().createStatement();
            ResultSet res = statement.executeQuery("Select * from siswa");
            while (res.next())
            {
                tbl.addRow(new Object []{
                    res.getString("NISN"),
                    res.getString("Nama"),
                    res.getString("NIK"),
                    res.getString("TTL"),
                    res.getString("Jurusan"),
                    res.getString("J_kelamin"),
                    res.getString("Agama"),
                    res.getString("S_asal"),
                    res.getString("No_hp"),
                    res.getString("Alamat"),
                });
                table.setModel(tbl);
            }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtnisn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnik = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtttl = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtagama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtsekolah = new javax.swing.JTextField();
        cbkelamin = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalamat = new javax.swing.JTextArea();
        bkeluar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txtcari = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtnohp = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btambah = new javax.swing.JButton();
        bsimpan = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cbjurusan = new javax.swing.JComboBox<>();
        bcetak = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NISN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));
        getContentPane().add(txtnisn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 247, -1));

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, 25));
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 247, -1));

        jLabel3.setText("NIK");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));
        getContentPane().add(txtnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 247, -1));

        jLabel4.setText("Tempat, Tanggal Lahir");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));
        getContentPane().add(txtttl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 247, -1));

        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, -1, -1));

        jLabel6.setText("Agama");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, -1));
        getContentPane().add(txtagama, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 273, -1));

        jLabel7.setText("Alamat");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, -1, -1));

        jLabel8.setText("No Handphone");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, 20));
        getContentPane().add(txtsekolah, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 273, -1));

        cbkelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));
        getContentPane().add(cbkelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 273, -1));

        txtalamat.setColumns(20);
        txtalamat.setRows(5);
        jScrollPane1.setViewportView(txtalamat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 273, 78));

        bkeluar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bkeluar.setText("Keluar");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(bkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("PENERIMAAN SISWA BARU MADRASAH ALIYYAH BANJARBARU");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 886, 190));
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 755, 31));

        bcari.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bcari.setText("Cari");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });
        getContentPane().add(bcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 320, 119, -1));

        jLabel10.setText("Sekolah Asal");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));
        getContentPane().add(txtnohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 273, -1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 102));

        btambah.setBackground(new java.awt.Color(255, 102, 102));
        btambah.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btambah.setForeground(new java.awt.Color(51, 51, 51));
        btambah.setText("Tambah");
        btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambahActionPerformed(evt);
            }
        });

        bsimpan.setBackground(new java.awt.Color(255, 102, 102));
        bsimpan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bsimpan.setForeground(new java.awt.Color(51, 51, 51));
        bsimpan.setText("Simpan");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        bedit.setBackground(new java.awt.Color(255, 102, 102));
        bedit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bedit.setForeground(new java.awt.Color(51, 51, 51));
        bedit.setText("Edit");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });

        bhapus.setBackground(new java.awt.Color(255, 102, 102));
        bhapus.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bhapus.setText("Hapus");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btambah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bedit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bhapus, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bhapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bedit)
                    .addComponent(bsimpan)
                    .addComponent(btambah))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel12.setText("Jurusan");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        cbjurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IPA", "IPS", "PAI" }));
        getContentPane().add(cbjurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 250, -1));

        bcetak.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bcetak.setText("Cetak Laporan");
        bcetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcetakActionPerformed(evt);
            }
        });
        getContentPane().add(bcetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/bgpendaftaran.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambahActionPerformed
      txtnisn.setText("");
      txtnama.setText("");
      txtnik.setText("");
      txtttl.setText("");
      cbjurusan.setSelectedItem("IPA");
      cbkelamin.setSelectedItem("Laki-laki");
      txtagama.setText("");
      txtsekolah.setText("");
      txtnohp.setText("");
      txtalamat.setText("");
      txtnisn.requestFocus();
    }//GEN-LAST:event_btambahActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        dispose();
    }//GEN-LAST:event_bkeluarActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        String NISN = txtnisn.getText();
        String Nama = txtnama.getText();
        String NIK = txtnik.getText();
        String TTL = txtttl.getText();
        String Jurusan = (String) cbjurusan.getSelectedItem();
        String J_kelamin = (String) cbkelamin.getSelectedItem();
        String Agama = txtagama.getText();
        String S_asal = txtsekolah.getText();
        String No_hp = txtnohp.getText();
        String Alamat = txtalamat.getText();

    try{
            try (Statement statement = (Statement) konek.getKonek().createStatement()) {
                statement.executeUpdate("insert into siswa VALUES ('" + NISN + "','" + Nama +"','"+ NIK +"','"+ TTL +"','"+ Jurusan +"','"+ J_kelamin +"','"+ Agama +"','"+ S_asal +"','"+ No_hp +"','"+ Alamat +"');");
            }
        JOptionPane.showMessageDialog(null, "Data Berhasil disimpan");
    }catch (HeadlessException | SQLException t){
        JOptionPane.showMessageDialog(null, "Data Gagal Disimpan");
    }
    datatable();
    }//GEN-LAST:event_bsimpanActionPerformed

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
         if("bedit".equals(bedit.getText())){
           txtnisn.requestFocus();
        }else{
            String NISN = txtnisn.getText();
            String Nama = txtnama.getText();
            String NIK = txtnik.getText();
            String TTL = txtttl.getText();
            String Jurusan = (String) cbjurusan.getSelectedItem();
	    String J_kelamin = (String) cbkelamin.getSelectedItem();
            String Agama = txtagama.getText();
            String S_asal = txtsekolah.getText();
            String No_hp = txtnohp.getText();
            String Alamat = txtalamat.getText();
            
        try{
                Statement statement = (Statement) konek.getKonek().createStatement();
                statement.executeUpdate("update siswa SET NISN='"+NISN+"',"+"Nama='"+Nama+"',"+"NIK='"+NIK+"',"+"TTL='"+TTL+"',"+"Jurusan='"+Jurusan+"',"+"J_kelamin='"+J_kelamin+"',"+"Agama='"+Agama+"',"+"S_asal='"+S_asal+"',"+"No_hp='"+No_hp+"',"+"Alamat='"+Alamat+"'" + "WHERE NISN = '"+NISN+"' OR Nama = '"+Nama+"'");
                statement.close();
            JOptionPane.showMessageDialog(null, "Data Berhasil diubah");
        }catch (HeadlessException | SQLException t){
            JOptionPane.showMessageDialog(null, "Data Gagal diubah");
        }
        datatable();
        }
    }//GEN-LAST:event_beditActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        String NISN = txtnisn.getText();
        String Nama = txtnama.getText();
        try{
            Statement statement = (Statement) konek.getKonek().createStatement();
            statement.executeUpdate("delete from siswa where NISN = '" + NISN + "' OR Nama ='" + Nama + "';");
            JOptionPane.showMessageDialog(null, "Data Berhasil di Hapus");
            txtnisn.setText("");
            txtnama.setText("");
            txtnik.setText("");
            txtttl.setText("");
            cbjurusan.setSelectedItem("IPA");
            cbkelamin.setSelectedItem("Laki-laki");
            txtagama.setText("");
            txtsekolah.setText("");
            txtnohp.setText("");
            txtalamat.setText("");
            txtnisn.requestFocus();
        }catch (HeadlessException | SQLException t){
            JOptionPane.showMessageDialog(null, "Data Gagal di Hapus");
        }
        datatable();
    }//GEN-LAST:event_bhapusActionPerformed

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
       try{
            Statement statement = (Statement) konek.getKonek().createStatement();
            ResultSet res = statement.executeQuery("Select * from siswa where "+"NISN like'%" + txtnisn.getText() + "%' OR "+"Nama like'%" + txtnama.getText() + "%'");
            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("NISN");
            tbl.addColumn("Nama");
            tbl.addColumn("NIK");
            tbl.addColumn("Tempat, Tanggal Lahir");
            tbl.addColumn("Jurusan");
            tbl.addColumn("Jenis Kelamin");
            tbl.addColumn("Agama");
            tbl.addColumn("Sekolah Asal");
            tbl.addColumn("No Handphone");
            tbl.addColumn("Alamat");
            table.setModel(tbl);
                while (res.next()){
                    tbl.addRow(new Object []{
                    res.getString("NISN"),
                    res.getString("Nama"),
                    res.getString("NIK"),
                    res.getString("TTL"),
                    res.getString("Jurusan"),
                    res.getString("J_kelamin"),
                    res.getString("Agama"),
                    res.getString("S_asal"),
                    res.getString("No_hp"),
                    res.getString("Alamat"),
                });
                table.setModel(tbl);
            }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(rootPane, "Error");
        }
    }//GEN-LAST:event_bcariActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int i = table.getSelectedRow();
        if (i == -1){
                return;
        }
	String NISN = (String) table.getValueAt(i, 0);
	txtnisn.setText(NISN);
	String Nama = (String) table.getValueAt(i, 1);
	txtnama.setText(Nama);
	String NIK = (String) table.getValueAt(i, 2);
	txtnik.setText(NIK);
        String TTL = (String) table.getValueAt(i, 3);
	txtttl.setText(TTL);
        String Jurusan = (String) table.getValueAt(i, 4);
	cbjurusan.setSelectedItem(Jurusan);
	String J_kelamin = (String) table.getValueAt(i, 5);
	cbkelamin.setSelectedItem(J_kelamin);
	String Agama = (String) table.getValueAt(i, 6);
	txtagama.setText(Agama);
        String S_asal = (String) table.getValueAt(i, 7);
	txtsekolah.setText(S_asal);
        String No_hp = (String) table.getValueAt(i, 8);
	txtnohp.setText(No_hp);
        String Alamat = (String) table.getValueAt(i, 9);
	txtalamat.setText(Alamat);
    }//GEN-LAST:event_tableMouseClicked

    private void bcetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcetakActionPerformed
        JOptionPane.showMessageDialog(null, "Harap Login Terlebih Dahulu!");
        new login().show();
    }//GEN-LAST:event_bcetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new siswa().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcari;
    private javax.swing.JButton bcetak;
    private javax.swing.JButton bedit;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton btambah;
    private javax.swing.JComboBox<String> cbjurusan;
    private javax.swing.JComboBox<String> cbkelamin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtagama;
    private javax.swing.JTextArea txtalamat;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnik;
    private javax.swing.JTextField txtnisn;
    private javax.swing.JTextField txtnohp;
    private javax.swing.JTextField txtsekolah;
    private javax.swing.JTextField txtttl;
    // End of variables declaration//GEN-END:variables
}
